linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - gofmt

linters-settings:
  misspell:
    locale: US

issues:
  exclude-use-default: true
